name: TypeScript Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tsc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # Test against multiple Node.js versions
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache dependencies
      - name: Install modules
        run: npm ci
      - name: Run type check
        run: npm run type-check
