name: TypeScript Check
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run type check
        run: npm run type-check
