name: TypeScript Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use cache for modules
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install modules
        run: npm ci
      - name: Run type check
        run: npm run type-check
